# derived from 
#<https://github.com/marketplace/actions/mkdocs-action>
#<https://gist.github.com/liflovs/f2a950dadcca25a0dbdfe10f53f5c838>
#<https://stackoverflow.com/questions/64374179/how-to-push-to-another-repository-in-github-actions>
#<https://stackoverflow.com/questions/41714882/git-how-to-clone-with-ssh-key-username>

name: mkdocs-build

on:
  push:
    branches:
      - main

jobs:

  build:
    name: build mkdocs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v4

      - name: Build
        uses: Tiryoh/actions-mkdocs@v0
        with:
          mkdocs_version: 'latest' # latest means latest for the base ubuntu image.  You should peg it to a specific version for best results.
          # mkdocs_version: '1.6' # option
          requirements: 'requirements.txt' # option
          configfile: 'mkdocs.yml' # option

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site          
          allow_empty_commit: true

